### ISSUE TITLE
启动json后error, 无法运行

### ISSUE THREAD

**Issue by Ihfu** [zgq354/weibo-rss#60]
部署在腾讯云 CentOS 7.6上的, 日志如下:

/root/weiborss/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/pwserver/weibo/dist/modules/weibo/api.js:7:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by Ihfu** [comment]
解决了 是因为 CentOS 7不能使用18版本及以上的nodejs
